import {
  ArrowRight, BadgeCheck, Banknote, BarChart3, Brain, Building2,
  CalendarClock, CheckCircle2, ChevronDown, ChevronUp, ClipboardCheck,
  ClipboardX, Clock, CreditCard, Cross, CircleHelp, Eye, Fingerprint,
  Footprints, Gauge, Headset, Hourglass, Landmark, Layers, LayoutGrid, Lock,
  MapPin, Megaphone, MessagesSquare, Phone, PlusCircle, RefreshCw, Route,
  Search, Send, Share2, Shield, ShieldCheck, Signal, Smartphone, Smile,
  Sparkles, ThumbsUp, Ticket, TrendingUp, TriangleAlert, Upload, UserCheck,
  Users, Wallet, WalletCards, X, Zap, Circle,
} from 'lucide-react';

const ICONS = {
  arrow_back: ArrowRight,
  arrow_forward: ArrowRight,
  arrowright: ArrowRight,
  add_circle: PlusCircle,
  close: X,
  send: Send,
  verified_user: BadgeCheck,
  verified: BadgeCheck,
  badgecheck: BadgeCheck,
  check_circle: CheckCircle2,
  circlecheck: CheckCircle2,
  checkcircle2: CheckCircle2,
  task_alt: CheckCircle2,
  schedule: CalendarClock,
  approval: ThumbsUp,
  lock: Lock,
  group: Users,
  users: Users,
  account_balance: Landmark,
  accountbalance: Landmark,
  location_on: MapPin,
  call: Phone,
  help: CircleHelp,
  visibility: Eye,
  report_problem: TriangleAlert,
  warning: TriangleAlert,
  grid_view: LayoutGrid,
  confirmation_number: Ticket,
  token: Ticket,
  alt_route: Route,
  hourglass_bottom: Hourglass,
  assignment_late: ClipboardX,
  sync_problem: RefreshCw,
  hub: Share2,
  forum: MessagesSquare,
  payments: Banknote,
  credit_card: CreditCard,
  creditcard: CreditCard,
  account_balance_wallet: Wallet,
  wallet: Wallet,
  psychology: Brain,
  analytics: BarChart3,
  smartphone: Smartphone,
  fact_check: ClipboardCheck,
  support_agent: Headset,
  auto_awesome: Sparkles,
  shield_person: UserCheck,
  policy: Shield,
  speed: Zap,
  cell_tower: Signal,
  local_hospital: Cross,
  services: Layers,
  stars: Sparkles,
  event_available: CalendarClock,
  bookings: CalendarClock,
  dashboard: LayoutGrid,
  notifications: BadgeCheck,
  settings: Gauge,
  directions_walk: Footprints,
  sentiment_very_satisfied: Smile,
  insights: TrendingUp,
  hourglass_top: Hourglass,
  campaign: Megaphone,
  search: Search,
  upload_file: Upload,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  building: Building2,
  building2: Building2,
  landmark: Landmark,
  fingerprint: Fingerprint,
  shieldcheck: ShieldCheck,
  wallecards: WalletCards,
};

export default function SvgIcon({ name, size = 20, className = '', strokeWidth = 1.8, ...rest }) {
  const key = String(name || '').toLowerCase().replace(/[\s-]/g, '').trim();
  const Icon = ICONS[key] || Circle;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...rest} />;
}

export { SvgIcon };